services:
  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - sail

  selenium:
    image: selenium/standalone-chromium
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - sail
